CREATE TABLE EMPLOYEES
   (	EMP_ID NUMBER(10,0),
	EMP_NAME VARCHAR2(100) NOT NULL ENABLE,
	HIRE_DATE DATE,
	SALARY NUMBER(10,2),
	IS_ACTIVE CHAR(1),
	COMMENTS CLOB,
	PROFILE_PIC BLOB,
	 PRIMARY KEY (EMP_ID)
  USING INDEX  ENABLE
   ) ;

